language: python
addons:
  apt:
    packages:
    - git

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get -yq update
  - sudo apt-get -yq install git
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH

  - evm config path /tmp
  - evm install $EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH

  - cask
install:
  - pip install jupyter==$JUPYTER
env:
  - EMACS=emacs-24.4-travis IPYCMD=jupyter JUPYTER=1.0.0
  - EMACS=emacs-25.1-travis IPYCMD=jupyter JUPYTER=1.0.0
  - EMACS=emacs-git-snapshot-travis IPYCMD=jupyter JUPYTER=1.0.0
script:
  - emacs --version
  - python tools/testein.py --emacs emacs --ipython $IPYCMD
 
