sudo: false
language: python

addons:
  apt:
    packages:
    - gnutls-bin
    - python-tornado
    - python3-tornado
    - python-zmq
    - python3-zmq
    - python-jinja2
    - python3-jinja2
    - python-jsonschema
    - python3-jsonschema

cache:
  directories:
  - $HOME/local

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH
  matrix:
    - EVM_EMACS=emacs-25.2-travis IPY_VERSION=5.8.0 EL_REQUEST_BACKEND=curl
    - EVM_EMACS=emacs-26.1-travis IPY_VERSION=6.2.1 EL_REQUEST_BACKEND=curl

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-snapshot

install:
  - pip install jupyter

before_script:
  - sh tools/install-evm.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - sh tools/install-cask.sh
  - cask install

script:
  - make test IPY_VERSION=$IPY_VERSION
