language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo apt-get remove -qq emacs
        sudo apt-get install -qq emacs24
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
install:
  - if [ "$JUPYTER" ]; then
       pip install jupyter==$JUPYTER
    fi
env:
  - EMACS=emacs24 IPYCMD=jupyter JUPYTER=1.0.0
  - EMACS=emacs-snapshot IPYCMD=jupyter JUPYTER=1.0.0
script: python tools/testein.py --emacs $EMACS --ipython $IPYCMD
 
