language: python
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - curl -fsSkl https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EMACS --use --skip
  - cask
install:
  - pip install jupyter==$JUPYTER
env:
  - EMACS=emacs-24.4-travis IPYCMD=jupyter JUPYTER=1.0.0
  - EMACS=emacs-25.1-travis IPYCMD=jupyter JUPYTER=1.0.0
  - EMACS=emacs-git-snapshot-travis IPYCMD=jupyter JUPYTER=1.0.0
script:
  - emacs --version
  - python tools/testein.py --emacs emacs --ipython $IPYCMD
 
